#!/bin/zsh

### BUILD THE SERVER IMAGE
# build for x86 (amd64) so it doesn't give 'exportfs: ./nfs_share does not support export' error (because macos uses a different file system from ext4)
docker build --tag "nfs-server:latest" --platform linux/amd64 --file ./server/nfsServerDockerfile ./server
### BUILD THE CLIENT IMAGE
docker build --tag "nfs-client:latest" --platform linux/amd64 --file ./client/nfsClientDockerfile ./client

# create a network
docker network create --driver bridge --subnet 192.168.0.0/16 nfs-net

# run the server container
docker run --detach --name nfs-server --privileged --platform linux/amd64 --network=nfs-net --ip=192.168.100.1 --publish 2049:2049 --volume ./nfs_share:/nfs_share nfs-server:latest /nfs_share
# run the client container
docker run --detach --name nfs-client --privileged --platform linux/amd64 --network=nfs-net --ip=192.168.100.2 nfs-client:latest /nfs_share:/shared

# get a shell on the client
docker exec -it <client_container> bash