#!/bin/bash

# source the NFS server (and files common to client and server) into environment
. /etc/default/nfs-kernel-server
. /etc/default/nfs-common

# start the server for converting RPC program numbers into universal addresses
# any client first contacts this RPC server, and then gets redirected to NFS server
rpcbind
# let the rpcbind fully start before starting nfs server
sleep 2

service nfs-kernel-server start
# reexport all exports
exportfs -ra

# wait for changes to '/export' directory (-m means monitor i.e. just log events)
echo "Monitoring changes in exports..."
exec inotifywait -m /exports